Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      # Set email as an alias
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        # customized attributes
        - Name: credit_card
          AttributeDataType: String
          Mutable: true

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

# Print out the Id of the User Pool that is created
Outputs:
  UserPoolId:
    Value: !Ref CognitoUserPool

  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
